create table address (id integer not null auto_increment, number integer not null, created_at datetime(6), fk_client_id bigint not null, updated_at datetime(6), city varchar(255) not null, country varchar(255) not null, neighborhood varchar(255) not null, state_or_county varchar(255) not null, street varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (dob date not null, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), country_id varchar(255) not null, email varchar(255) not null, first_name varchar(255) not null, second_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table order_main (finalized bit, id integer not null auto_increment, total_sum float(23) not null, created_at datetime(6), fk_client_id bigint not null, updated_at datetime(6), primary key (id)) engine=InnoDB;
create table order_product (amount integer, unit_price float(23) not null, fk_order_id bigint not null auto_increment, fk_product_id bigint not null, id bigint not null, product_name varchar(255) not null, primary key (fk_order_id, fk_product_id, id)) engine=InnoDB;
create table product (active bit not null, fk_category_id integer, unit_price float(23) not null, units_in_stock integer not null, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), description varchar(255) not null, image_url varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table product_category (id integer not null auto_increment, created_at datetime(6), updated_at datetime(6), name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table address add constraint UK_opwmfjix5d7aul7jg7gqhqlo8 unique (fk_client_id);
alter table address add constraint FKagg3d6rjs3qe9y1j1blwv06nm foreign key (fk_client_id) references client (id);
alter table order_main add constraint FKedp7cnj6ia1l8djrbqiygp190 foreign key (fk_client_id) references client (id);
alter table order_product add constraint FK8bv9j4mbsqmt4xbl5wo71clc0 foreign key (fk_product_id) references product (id);
alter table order_product add constraint FKmt7hdi59xjbvbialb3bxx8kwu foreign key (fk_order_id) references order_main (id);
alter table product add constraint FK46h9w3nrbyyjff2rc5xvned6o foreign key (fk_category_id) references product_category (id);
create table address (id integer not null auto_increment, number integer not null, created_at datetime(6), fk_client_id bigint not null, updated_at datetime(6), city varchar(255) not null, country varchar(255) not null, neighborhood varchar(255) not null, state_or_county varchar(255) not null, street varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (dob date not null, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), country_id varchar(255) not null, email varchar(255) not null, first_name varchar(255) not null, second_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table order_main (finalized bit, id integer not null auto_increment, total_sum float(23) not null, created_at datetime(6), fk_client_id bigint not null, updated_at datetime(6), primary key (id)) engine=InnoDB;
create table order_product (amount integer, unit_price float(23) not null, fk_order_id bigint not null auto_increment, fk_product_id bigint not null, id bigint not null, product_name varchar(255) not null, primary key (fk_order_id, fk_product_id, id)) engine=InnoDB;
create table product (active bit not null, fk_category_id integer, unit_price float(23) not null, units_in_stock integer not null, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), description varchar(255) not null, image_url varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table product_category (id integer not null auto_increment, created_at datetime(6), updated_at datetime(6), name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table address add constraint UK_opwmfjix5d7aul7jg7gqhqlo8 unique (fk_client_id);
alter table address add constraint FKagg3d6rjs3qe9y1j1blwv06nm foreign key (fk_client_id) references client (id);
alter table order_main add constraint FKedp7cnj6ia1l8djrbqiygp190 foreign key (fk_client_id) references client (id);
alter table order_product add constraint FK8bv9j4mbsqmt4xbl5wo71clc0 foreign key (fk_product_id) references product (id);
alter table order_product add constraint FKmt7hdi59xjbvbialb3bxx8kwu foreign key (fk_order_id) references order_main (id);
alter table product add constraint FK46h9w3nrbyyjff2rc5xvned6o foreign key (fk_category_id) references product_category (id);
